### ISSUE TITLE
Can it use the APFS format?

### ISSUE THREAD

**Issue by longgegeno1** [munki/installr#1]
Can it use the APFS format?
I notice the HFS+ in the make_dmg.sh file.
"/usr/bin/hdiutil create -fs HFS+ -srcfolder "${THISDIR}/install" "${DMGNAME}""

**Comment by gregneagle** [comment]
Probably, but what would be the advantage?  Hfs+ disk images would work back to 10.12 well and maybe even earlier...

**Comment by longgegeno1** [comment]
We don't need to support the earlier devices or OS versions.
If the APFS is the future,we'd better use it.

**Comment by gregneagle** [comment]
Feel free to do so in your own script.

**Comment by longgegeno1** [comment]
Thanks
