### ISSUE TITLE
Error on Big Sur

### ISSUE THREAD

**Issue by alby696** [munki/installr#12]
HI,

I tested the scrypt and everything works without problems with High Sierra, Mojave and Catalina.
As for Big Sur, it starts the process but then logout without doing anything.

I noticed that the construction of the installation package is different, it is no longer called installESD but Shared Support.

I don't know how to fix it, as the terminal command from machine started and Big Sur inside the Applications folder works but from remote dmg recovery it goes wrong.

Thank you for your answer.

alby696

**Comment by gregneagle** [comment]
Big Sur’s `startosinstall` fails to run under pre-Big Sur Recovery. Only Apple could fix this if they cared to.

**Comment by alby696** [comment]
Thanks a lot for the tip, I thought it was a problem that I was wrong to compile the file or the installer I downloaded.

I hope they will solve it soon because otherwise it would be impossible to upgrade any machine unless you have an administrator pass and a booted system.

alby696

**Comment by gregneagle** [comment]
I do not think Apple considers it a problem that they need to fix
