### ISSUE TITLE
Reboot failed after osinstall

### ISSUE THREAD

**Issue by StevieShizzles** [munki/installr#5]
osinstall starts and completes

error : system reboot failed

when rebooted, folder with questionmark is displayed

**Comment by StevieShizzles** [comment]
no one? :)

**Comment by gregneagle** [comment]
Sounds like the `startosinstall` tool failed. That's _Apple's_ tool.

Can you reproduce?
What happens if you take `installr` out of the equation and run `startosinstall` directly?

I'd look for clues in /var/log/install.log...

**Comment by chrisgrande** [comment]
I had this issue - was caused by a damaged macOS installer

**Comment by gregneagle** [comment]
Closing old issue we haven't reproduced with no new info in 9+ months.
