### ISSUE TITLE
Advanced select

### ISSUE THREAD

**Issue by alby696** [munki/installr#6]
Hi everyone,
by chance it is possible to implement the possibility of choosing some macos installer to use and whether to install pkg or not?
In the sense if I have 10.13 and 10.14 I decide which one to install without having to create USB or different dmg files.

Thank you
alby696

**Comment by gregneagle** [comment]
Installr is a very simple shell script that meets my needs. I've shared it freely. If it does not meet your needs, feel free to use Installr as a starting point and modify it to meet your own needs.
