### ISSUE TITLE
install.Rtools() current version malfunction

### ISSUE THREAD

**Issue by Krisselack** [munki/installr#7]
install.Rtools() for the current version 3.5 led to the following: 

> Please remember you are using:  R version 3.6.0 (2019-04-26) 
> tryURL 'https://cran.r-project.org/bin/windows/Rtools/Rtools35.exe (recommended)'
> Explanation of the error: You didn't enter a valid .EXE URL. 

I think, the (recommended) was pasted after the .exe.

**Comment by gregneagle** [comment]
What does this have to do with installr?

If you mean the "install.Rtools()" installer fails in the installr environment, then that is unfortunate, but not installr's fault.

installr does not claim to be able to install every piece of software out there; quite the opposite, actually. It is intended to help you bootstrap your real software management tools, generally using a small number of packages that are in your control.

**Comment by gregneagle** [comment]
Oh, I think you have the wrong project entirely.

**Comment by Krisselack** [comment]
Ah yeah, I see. Sorry for the fuss, it was just a quick search and paste. I meant this function, will write to the guy: https://www.rdocumentation.org/packages/installr/versions/0.21.0/topics/install.Rtools
