### ISSUE TITLE
Recovery mode - CURL error code 4 translated to 22

### ISSUE THREAD

**Issue by iampavan** [munki/installr#9]
I've created 10.13.6.dmg and 10.14.6.dmg using the script and hosting them on an internal webserver.

When I've booted into the OS and run the command `hdiutil attach http://abc.com/installr/10.13.6.dmg -verbose`, it works perfectly.

Here's the verbose output I see :

> Initialising…
> CBSDBackingStore::newProbe not file: scheme.
> DIBackingStoreInstantiatorProbe: interface  0, score    -1000, CBSDBackingStore
> DIBackingStoreInstantiatorProbe: interface  1, score    -1000, CBundleBackingStore
> DIBackingStoreInstantiatorProbe: interface  2, score    -1000, CRAMBackingStore
> DIBackingStoreInstantiatorProbe: interface  3, score    -1000, CCarbonBackingStore
> DIBackingStoreInstantiatorProbe: interface  4, score    -1000, CDevBackingStore
> DIBackingStoreInstantiatorProbe: interface  5, score      200, CCURLBackingStore
> DIBackingStoreInstantiatorProbe: interface  6, score    -1000, CVectoredBackingStore
> CBSDBackingStore::newProbe not file: scheme.
> DIBackingStoreInstantiatorProbe: interface  0, score    -1000, CBSDBackingStore
> DIBackingStoreInstantiatorProbe: interface  1, score    -1000, CBundleBackingStore
> DIBackingStoreInstantiatorProbe: interface  2, score    -1000, CRAMBackingStore
> DIBackingStoreInstantiatorProbe: interface  3, score    -1000, CCarbonBackingStore
> DIBackingStoreInstantiatorProbe: interface  4, score    -1000, CDevBackingStore
> DIBackingStoreInstantiatorProbe: interface  5, score      200, CCURLBackingStore
> DIBackingStoreInstantiatorProbe: interface  6, score    -1000, CVectoredBackingStore
> DIFileEncodingInstantiatorProbe: interface  0, score    -1000, CMacBinaryEncoding
> DIFileEncodingInstantiatorProbe: interface  1, score    -1000, CAppleSingleEncoding
> DIFileEncodingInstantiatorProbe: interface  2, score    -1000, CEncryptedEncoding
> DIFileEncodingInstantiatorProbe: interface  0, score      900, CUDIFEncoding
> DIFileEncodingNewWithBackingStore: CUDIFEncoding
> DIFileEncodingNewWithBackingStore: instantiator returned 0
> DIFileEncodingInstantiatorProbe: interface  0, score    -1000, CSegmentedNDIFEncoding
> DIFileEncodingInstantiatorProbe: interface  1, score    -1000, CSegmentedUDIFEncoding
> DIFileEncodingInstantiatorProbe: interface  2, score    -1000, CSegmentedUDIFRawEncoding
> DIDiskImageInstantiatorProbe: interface  0, score     1000, CUDIFDiskImage
> DIDiskImageInstantiatorProbe: interface  1, score        0, CSparseBundleDiskImage
> DIDiskImageInstantiatorProbe: interface  2, score        0, CSparseDiskImage
> CRawDiskImage: data fork length 0x000000013B5D4ADA (5290937050) not a multiple of 512.
> DIDiskImageInstantiatorProbe: interface  3, score     -100, CRawDiskImage
> DIDiskImageInstantiatorProbe: interface  4, score        0, CDARTDiskImage
> DIDiskImageInstantiatorProbe: interface  5, score        0, CDiskCopy42DiskImage
> DIDiskImageInstantiatorProbe: interface  6, score    -1000, CNDIFDiskImage
> DIDiskImageInstantiatorProbe: interface  8, score     -100, CShadowedDiskImage
> DIDiskImageInstantiatorProbe: interface  9, score    -1000, CCFPlugInDiskImage
> DIDiskImageInstantiatorProbe: interface 10, score     -100, CWrappedDiskImage
> DIDiskImageNewWithBackingStore: CUDIFDiskImage
> DIDiskImageNewWithBackingStore: instantiator returned 0
> Attaching…
> Mounting…
> 2019-08-06 16:39:02.779 diskimages-helper[44566:1554993] DIHelperHDID serveImage: attaching drive
> {
>     autodiskmount = 1;
>     "hdiagent-drive-identifier" = "B1F53B65-3EB0-4DE5-AA2C-874CA9A896C5";
>     "unmount-timeout" = 0;
> }
> 2019-08-06 16:39:02.780 diskimages-helper[44566:1554993] DIHelperHDID serveImage: connecting to myDrive 0x430B
> 2019-08-06 16:39:02.780 diskimages-helper[44566:1554993] DIHelperHDID serveImage: register _readBuffer 0x10d0ed000
> 2019-08-06 16:39:02.780 diskimages-helper[44566:1554993] DIHelperHDID serveImage: activating drive port 13835
> 2019-08-06 16:39:02.780 diskimages-helper[44566:1554993] DIHelperHDID serveImage: set cache enabled=TRUE returned SUCCESS.
> 2019-08-06 16:39:02.780 diskimages-helper[44566:1554993] DIHelperHDID serveImage: set on IO thread=TRUE returned SUCCESS.
> 2019-08-06 16:39:02.780 diskimages-helper[44566:1554993] -processKernelRequest: will sleep received
> 2019-08-06 16:39:03.893 diskimages-helper[44566:1554918] _postflightMountPointsAfterDAMount: disk4s1 aborting because no mount point found.
> 2019-08-06 16:39:03.893 diskimages-helper[44566:1554921] _postflightMountPointsAfterDAMount: disk4s1 aborting because no mount point found.
> 2019-08-06 16:39:03.893 diskimages-helper[44566:1554918] _postflightMountPointsAfterDAMount: disk4s2 aborting because disk image has no band size specified.
> 2019-08-06 16:39:03.894 diskimages-helper[44566:1554921] _postflightMountPointsAfterDAMount: disk4s2 aborting because disk image has no band size specified.
> 2019-08-06 16:39:03.894 diskimages-helper[44566:1554918] _postflightMountPointsAfterDAMount: disk4 aborting because no mount point found.
> 2019-08-06 16:39:03.894 diskimages-helper[44566:1554921] _postflightMountPointsAfterDAMount: disk4 aborting because no mount point found.
> Finishing…
> Finishing…
> /dev/disk4          	GUID_partition_scheme
> /dev/disk4s1        	EFI
> /dev/disk4s2        	Apple_HFS                      	/Volumes/install

But when I run from Recovery / Internet recovery, I get an error:

> Initialising…
> CBSDBackingStore::newProbe not file: scheme.
> DIBackingStoreInstantiatorProbe: interface  0, score    -1000, CBSDBackingStore
> DIBackingStoreInstantiatorProbe: interface  1, score    -1000, CBundleBackingStore
> DIBackingStoreInstantiatorProbe: interface  2, score    -1000, CRAMBackingStore
> DIBackingStoreInstantiatorProbe: interface  3, score    -1000, CCarbonBackingStore
> DIBackingStoreInstantiatorProbe: interface  4, score    -1000, CDevBackingStore
> DIBackingStoreInstantiatorProbe: interface  5, score      200, CCURLBackingStore
> DIBackingStoreInstantiatorProbe: interface  6, score    -1000, CVectoredBackingStore
> CBSDBackingStore::newProbe not file: scheme.
> DIBackingStoreInstantiatorProbe: interface  0, score    -1000, CBSDBackingStore
> DIBackingStoreInstantiatorProbe: interface  1, score    -1000, CBundleBackingStore
> DIBackingStoreInstantiatorProbe: interface  2, score    -1000, CRAMBackingStore
> DIBackingStoreInstantiatorProbe: interface  3, score    -1000, CCarbonBackingStore
> DIBackingStoreInstantiatorProbe: interface  4, score    -1000, CDevBackingStore
> DIBackingStoreInstantiatorProbe: interface  5, score      200, CCURLBackingStore
> DIBackingStoreInstantiatorProbe: interface  6, score    -1000, CVectoredBackingStore
> CURL error code 4 translated to 22
> CURL's error message: ?@n
> CCURLBackingStore::statImage failed. returning 22
> Attaching...
> Error 22 (Invalid argument).
> Finishing...
> DIHLDiskImageAttach() Return 22

When I run from the thumb drive, it works perfectly in Recovery mode too.
What might be the issue?

**Comment by gregneagle** [comment]
Since it works from a thumb drive the issue cannot be with the disk image.
Since you are getting:
```
CURL error code 4 translated to 22
CURL's error message: ?@n
CCURLBackingStore::statImage failed. returning 22
Attaching...
Error 22 (Invalid argument).
Finishing...
DIHLDiskImageAttach() Return 22
```
we can conclude that it's a web server/HTTP issue. I've never seen this, and have had no other reports of it, so I don't have any additional suggestions.

**Comment by iampavan** [comment]
No worries, thanks for your response though. I'll let you know if I find something.

**Comment by gregneagle** [comment]
Closing old issue since there has been no new information in six months.

**Comment by urielha** [comment]
@iampavan Have you managed to solve this? I'm getting same error trying to download from an internal server

**Comment by urielha** [comment]
Just for the sake of documentation:

I believe the error was with `curl` not handling https protocol (when I tried `curl https://<my-server>/` it failed with the error "protocol or option was not found built-in in this libcurl due to a build-time")

I ended up:
 - Downloading the dmg on another computer
 - Transfer the file via usb stick
 - Using `hdiutil attach /Volumes/<STICK NAME>/<file name>.dmg`

Pay attention not to remove the stick before you done.

**Comment by iampavan** [comment]
> @iampavan Have you managed to solve this? I'm getting same error trying to download from an internal server

Sorry, no. I haven't looked at it
